name: check_docs

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2
    - name: Upgrade pip
      run: |
        pip install --upgrade pip
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install package
      run: |
        pip install -e .
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y g++ && apt-get install -y gfortran && apt-get install -y pandoc"
        docs-folder: "docs/"
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/_build/html/
    # Skip publishing built docs to gh-pages branch.
