name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v4
    - name: Lint
      uses: psf/black@stable
      with:
          version: "23.7.0"
    - name: Setup python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade jupyter matplotlib
    - name: Build and install
      run: |
        python -m pip install .
    - name: Run tutorial to test
      working-directory: docs/notebooks
      run: |
        jupyter nbconvert --to script XFaster_Tutorial.ipynb
        python XFaster_Tutorial.py
