name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade jupyter matplotlib
    - name: Build and install
      run: |
        python -m pip install -e .
    - name: Run tutorial to test
      run: |
        jupyter nbconvert --to script docs/notebooks/XFaster_Tutorial.ipynb
        python docs/notebooks/XFaster_Tutorial.py
